package ma.ac.emi.info.JobRecommandationsApp.Entities;


public enum Competence {
    PROGRAMMATION,
    DESIGN_GRAPHIQUE,
    MARKETING_DIGITAL,
    GESTION_DE_PROJET,
    COMMUNICATION,
    VENTE,
    ANALYSE_DE_DONNEES,
    GESTION_DE_LA_RELATION_CLIENT,
    RESSOURCES_HUMAINES,
    COMPTABILITÉ
}